BOOTMAGIC_ENABLE = no
COMMAND_ENABLE = no
CONSOLE_ENABLE = no
DEBUG_ENABLE = no
EXTRAKEY_ENABLE = yes
FORCE_NKRO = no
KEY_LOCK_ENABLE = yes
LEADER_ENABLE = yes
MIDI_ENABLE = no
MOUSEKEY_ENABLE = no
NKRO_ENABLE = yes
RAW_ENABLE = yes
RGBLIGHT_ENABLE = yes
SLEEP_LED_ENABLE = no
TAP_DANCE_ENABLE = yes
UCIS_ENABLE = no

LTO_ENABLE = yes

SRC += users/nwf/raw_hid.c
SRC += $(dir $(KEYMAP_C))leds.c
